name: Deploy Bot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd /root/AutoChinaBot
            git pull origin main
            docker build -t china-bot .
            docker stop china-bot-container || true
            docker rm china-bot-container || true
            docker run -d --name china-bot-container \
              -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
              -p 8000:8000 \
              china-bot
